#!/bin/bash
# ------------------------------------------------------------
# script:  cleanpuppetnodes
# Author:  Esteban M. Navas Martín
# Date:    12-01-2017
# Ver:     13-01-2017
#
# Purpose: This program cleans the following puppet node info: facts, node and certificate
#
# Copyright (c) 2012-2017 Esteban M. Navas Martín <adminies.valledeljerte@edu.juntaextremadura.net>. All rights reserved.

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.


# Comprobamos si se han introducido la antigüedad como parámetro
if [ $# -lt 1 ]; then
   ANTIGUEDADMAX="90" # antigüedad máxima por defecto
else
   ANTIGUEDADMAX=$1
fi

:> /tmp/puppetclean.tmp

antsyslog=$(stat -c %Y /var/log/syslog)

facts_dir="$(find /opt/puppetlabs -path '*/yaml/facts')"

[ -z $facts_dir ] && exit 1

for fichero in $(ls $facts_dir/* 2>/dev/null); do
   # Calculamos la diferencia
   antfichero=$(stat -c %Y $fichero)
   diferencia=$((antsyslog-antfichero))

   DIAS=$((diferencia/60/60/24))
   hostname=$(sed -n 's|fqdn:\(.*\)|\1|p' $fichero | sed -e 's/^[ \t]*//')
   archivo=$(basename $fichero)
   uuid=$(echo "${archivo%.*}")

   if [ $DIAS -ge $ANTIGUEDADMAX ]; then
      echo "Cleaning puppet node $uuid ($hostname): $DIAS days old"
      puppet node clean $uuid
   else
      echo "$diferencia:$hostname:$fichero" >> /tmp/puppetclean.tmp
   fi
done

sort -o /tmp/puppetclean.tmp -t':' -k2,1 /tmp/puppetclean.tmp
sort -t':' -k2,2 /tmp/puppetclean.tmp | cut -f2 -d":" |uniq -d > /tmp/dupnodes.tmp

for nodo in $(cat /tmp/dupnodes.tmp); do
    grep $nodo /tmp/puppetclean.tmp | tail -n +2 | cut -f3 -d":" > /tmp/dupcerts.tmp

    for fichero in $(cat /tmp/dupcerts.tmp); do
        hostname=$(sed -n 's|fqdn:\(.*\)|\1|p' $fichero | sed -e 's/^[ \t]*//')
        archivo=$(basename $fichero)
        uuid=$(echo "${archivo%.*}")
        echo "Cleaning old puppet node $uuid ($hostname)"
        puppet node clean $uuid
    done
done
